[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 3001
  port = 3001
  publish = "dist"
  autoLaunch = true
  environment = { NODE_ENV = "development" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co https://*.netlify.app;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://*.netlify.app https://accounts.google.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https://*.supabase.co https://*.googleusercontent.com;
      font-src 'self';
      connect-src 'self' https://*.supabase.co https://*.netlify.app https://accounts.google.com;
      frame-src https://accounts.google.com;
    """

[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm run build"
  environment = { NODE_ENV = "production" } 